require('dotenv').config();
const Sequelize = require('sequelize');

const sequelize = new Sequelize(process.env.DATABASE, process.env.DB_USER, process.env.DB_PASS, {
  host: process.env.DB_HOST,
  dialect: 'mysql'
});



module.exports = sequelize;
///KAJDKSFJASDKFJAKSDJFKASJDFAKSDJFKADSJKFAKSDJFKASDJKFAKSJDFKASJDFKAJSDFKAJSDFJKAJSDKFAJKSDFKJASDJKFAJKSDFJKASJDKFAKJSDFKASDJFKAJKSDFKAJSDFKAJSDKFJAKSDJFAKSDJFAKSDJFAKSDJFKASDJFKASJDFALKSDJFALSKDJFALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKFJALSDKJADLSKFJALSDKFJALSKDFJALSKDFJALSDKJFALSDKFJALSKDJFALKSDJFALSDKJFALSKDJFALKSDJFALSDKJFALSDKJFAS



// CLOSE ALL YOUR VSCODES AND ONLY OPEN ONE VSCODE AND IT SHOULD WORK! :)
